title: thomas capogreco
description: I suppose this is where the description goes?
theme: jekyll-theme-minimal
baseurl: "thomas.capogre.co"


# lsi: false
# safe: true
# source:
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
